# ROS1 private parameters for node chassis_driver_node
# Load this file in launch under the node scope.

topic_prefix: /yunle_chassis

publish_raw_can: true
publish_unknown_frames: true
enable_debug_topics: true

default_qos_depth: 10

enabled_publish_topics:
  - all

enabled_subscribe_topics:
  - all

message_channel_map:
  - "BMS_Status:can2"
  - "BMS_Realtime_Status:can2"
  - "VCU_Warning_Level:can2"
  - "VCU_Wheel_Speed_Feedback:can2"
  - "VCU_CCU_Status:can2"
  - "SAS_Angle_Feedback:can2"
  - "SCU_Target_Speed_Feedback:can2"

control_message_channel_map:
  - "SCU_Control_Command:can2"
  - "SCU_Chassis_Command:can2"
  - "SCU_Torque_Command:can2"

local_ip: 192.168.1.102
can1_local_port: 8234
can2_local_port: 8235

can1_remote_ip: 192.168.1.98
can2_remote_ip: 192.168.1.99
remote_port: 1234

udp_buffer_size: 2048
socket_timeout_ms: 200
