chassis_driver_node:
  ros__parameters:
    topic_prefix: /chassis
    publish_raw_can: true
    publish_unknown_frames: true
    enable_debug_topics: true
    default_qos_depth: 10
    message_channel_map:
      - "BMS_Status:can1"
      - "BMS_Realtime_Status:can1"
      - "VCU_Warning_Level:can1"
      - "VCU_Wheel_Speed_Feedback:can2"
      - "VCU_CCU_Status:can1"
      - "SAS_Angle_Feedback:can2"
      - "SCU_Target_Speed_Feedback:can1"
    control_message_channel_map:
      - "SCU_Control_Command:can1"
      - "SCU_Chassis_Command:can1"
      - "SCU_Torque_Command:can2"
